issues:
  exclude-dirs:
    - vendor

  exclude-files:
    - ".*\\_test.go$"

linters:
  disable-all: true
  enable:
    - gofmt
    - errcheck
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - nosprintfhostport
    - staticcheck
    - typecheck
    - unused
    - exportloopref
